# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: music_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'music_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13music_service.proto\x12\x05music\"\x07\n\x05\x45mpty\"$\n\x0eUsuarioRequest\x12\x12\n\nusuario_id\x18\x01 \x01(\x05\"&\n\x0fPlaylistRequest\x12\x13\n\x0bplaylist_id\x18\x01 \x01(\x05\"\"\n\rMusicaRequest\x12\x11\n\tmusica_id\x18\x01 \x01(\x05\"#\n\x07Usuario\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\"5\n\x06Musica\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x0f\n\x07\x61rtista\x18\x03 \x01(\t\"I\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x12\n\nusuario_id\x18\x03 \x01(\x05\x12\x0f\n\x07musicas\x18\x04 \x03(\x05\"4\n\x10UsuariosResponse\x12 \n\x08usuarios\x18\x01 \x03(\x0b\x32\x0e.music.Usuario\"1\n\x0fMusicasResponse\x12\x1e\n\x07musicas\x18\x01 \x03(\x0b\x32\r.music.Musica\"7\n\x11PlaylistsResponse\x12\"\n\tplaylists\x18\x01 \x03(\x0b\x32\x0f.music.Playlist2\xcf\x02\n\x0cMusicService\x12\x34\n\x0bGetUsuarios\x12\x0c.music.Empty\x1a\x17.music.UsuariosResponse\x12\x32\n\nGetMusicas\x12\x0c.music.Empty\x1a\x16.music.MusicasResponse\x12\x46\n\x13GetPlaylistsUsuario\x12\x15.music.UsuarioRequest\x1a\x18.music.PlaylistsResponse\x12\x44\n\x12GetMusicasPlaylist\x12\x16.music.PlaylistRequest\x1a\x16.music.MusicasResponse\x12G\n\x15GetPlaylistsComMusica\x12\x14.music.MusicaRequest\x1a\x18.music.PlaylistsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'music_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_USUARIOREQUEST']._serialized_start=39
  _globals['_USUARIOREQUEST']._serialized_end=75
  _globals['_PLAYLISTREQUEST']._serialized_start=77
  _globals['_PLAYLISTREQUEST']._serialized_end=115
  _globals['_MUSICAREQUEST']._serialized_start=117
  _globals['_MUSICAREQUEST']._serialized_end=151
  _globals['_USUARIO']._serialized_start=153
  _globals['_USUARIO']._serialized_end=188
  _globals['_MUSICA']._serialized_start=190
  _globals['_MUSICA']._serialized_end=243
  _globals['_PLAYLIST']._serialized_start=245
  _globals['_PLAYLIST']._serialized_end=318
  _globals['_USUARIOSRESPONSE']._serialized_start=320
  _globals['_USUARIOSRESPONSE']._serialized_end=372
  _globals['_MUSICASRESPONSE']._serialized_start=374
  _globals['_MUSICASRESPONSE']._serialized_end=423
  _globals['_PLAYLISTSRESPONSE']._serialized_start=425
  _globals['_PLAYLISTSRESPONSE']._serialized_end=480
  _globals['_MUSICSERVICE']._serialized_start=483
  _globals['_MUSICSERVICE']._serialized_end=818
# @@protoc_insertion_point(module_scope)
