# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import music_service_pb2 as music__service__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in music_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MusicServiceStub:
    """── Serviço ───────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsuarios = channel.unary_unary(
                '/music.MusicService/GetUsuarios',
                request_serializer=music__service__pb2.Empty.SerializeToString,
                response_deserializer=music__service__pb2.UsuariosResponse.FromString,
                _registered_method=True)
        self.GetMusicas = channel.unary_unary(
                '/music.MusicService/GetMusicas',
                request_serializer=music__service__pb2.Empty.SerializeToString,
                response_deserializer=music__service__pb2.MusicasResponse.FromString,
                _registered_method=True)
        self.GetPlaylistsUsuario = channel.unary_unary(
                '/music.MusicService/GetPlaylistsUsuario',
                request_serializer=music__service__pb2.UsuarioRequest.SerializeToString,
                response_deserializer=music__service__pb2.PlaylistsResponse.FromString,
                _registered_method=True)
        self.GetMusicasPlaylist = channel.unary_unary(
                '/music.MusicService/GetMusicasPlaylist',
                request_serializer=music__service__pb2.PlaylistRequest.SerializeToString,
                response_deserializer=music__service__pb2.MusicasResponse.FromString,
                _registered_method=True)
        self.GetPlaylistsComMusica = channel.unary_unary(
                '/music.MusicService/GetPlaylistsComMusica',
                request_serializer=music__service__pb2.MusicaRequest.SerializeToString,
                response_deserializer=music__service__pb2.PlaylistsResponse.FromString,
                _registered_method=True)


class MusicServiceServicer:
    """── Serviço ───────────────────────────────────────────────────────────────────

    """

    def GetUsuarios(self, request, context):
        """GET /usuarios
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMusicas(self, request, context):
        """GET /musicas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistsUsuario(self, request, context):
        """GET /usuarios/<usuario_id>/playlists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMusicasPlaylist(self, request, context):
        """GET /playlists/<playlist_id>/musicas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistsComMusica(self, request, context):
        """GET /musicas/<musica_id>/playlists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MusicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsuarios,
                    request_deserializer=music__service__pb2.Empty.FromString,
                    response_serializer=music__service__pb2.UsuariosResponse.SerializeToString,
            ),
            'GetMusicas': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMusicas,
                    request_deserializer=music__service__pb2.Empty.FromString,
                    response_serializer=music__service__pb2.MusicasResponse.SerializeToString,
            ),
            'GetPlaylistsUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistsUsuario,
                    request_deserializer=music__service__pb2.UsuarioRequest.FromString,
                    response_serializer=music__service__pb2.PlaylistsResponse.SerializeToString,
            ),
            'GetMusicasPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMusicasPlaylist,
                    request_deserializer=music__service__pb2.PlaylistRequest.FromString,
                    response_serializer=music__service__pb2.MusicasResponse.SerializeToString,
            ),
            'GetPlaylistsComMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistsComMusica,
                    request_deserializer=music__service__pb2.MusicaRequest.FromString,
                    response_serializer=music__service__pb2.PlaylistsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'music.MusicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('music.MusicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MusicService:
    """── Serviço ───────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def GetUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetUsuarios',
            music__service__pb2.Empty.SerializeToString,
            music__service__pb2.UsuariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMusicas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetMusicas',
            music__service__pb2.Empty.SerializeToString,
            music__service__pb2.MusicasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistsUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetPlaylistsUsuario',
            music__service__pb2.UsuarioRequest.SerializeToString,
            music__service__pb2.PlaylistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMusicasPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetMusicasPlaylist',
            music__service__pb2.PlaylistRequest.SerializeToString,
            music__service__pb2.MusicasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistsComMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetPlaylistsComMusica',
            music__service__pb2.MusicaRequest.SerializeToString,
            music__service__pb2.PlaylistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
